apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-deployment
spec:
  selector:
    matchLabels:
      app: chat-pod
  template:
    metadata:
      labels:
        app: chat-pod
    spec:
      containers:
      - name: chat-container
        image: benhassan98/chat-service-image
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: chat-service
spec:
  selector:
    app: chat-pod
  ports:
  - name: chat-service-port
    protocol: TCP
    port: 8080
    targetPort: 8080
                                                                                                                                    
